### ISSUE TITLE
Auto-deploy

### ISSUE THREAD

**Issue by marctorsoc** [ynqa/pandavro#36]
I see that the config is 

```
deploy:
  provider: pypi
  user: pyncha
  password:
    secure: ****
  on:
    tags: true
    python: 3.9
```

so it doesn't auto-release https://pypi.org/project/pandavro/#history. Not being an expert in travis, it looks to me like it will only release a new version once you manually add a tag to a branch, as explained in https://docs.travis-ci.com/user/deployment/pypi/#deploying-tags. Wouldn't be easier just to release every time you merge on master? i.e:

```
  on:
    branch: master
```

as explained here: https://docs.travis-ci.com/user/deployment/pypi/#deploying-specific-branches

WDYT?
